spring:
  datasource:
    url: ${AUTH_ILOGOS_DB_URL}
    username: ${DB_ILOGOS_USERNAME}
    password: ${DB_ILOGOS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${ILOGOS_JWT_SECRET}
  accessTokenExpiration: 28800000   # 8 hours
  refreshTokenExpiration: 604800000 # 7 days
