create table app_user (
	id uuid not null,
	username varchar(255) not null unique,
	email varchar(255) not null unique,
	active boolean,
	email_verified boolean,
	failed_attempts integer not null,
	created_at timestamp(6) with time zone not null,
	last_login_at timestamp(6) with time zone,
	last_token_issued_at timestamp(6) with time zone not null,
	password_changed_at timestamp(6) with time zone,
	prev_login_at timestamp(6) with time zone,
	updated_at timestamp(6) with time zone,
	password varchar(255) not null,
	timezone varchar(255) not null,
	primary key (id));
create table email_history (
	id bigint generated by default as identity,
	user_id uuid not null,
	email varchar(255) not null,
	start_at timestamp(6) with time zone not null,
	end_at timestamp(6) with time zone,
	primary key (id));
create table user_roles (
	user_id uuid not null,
	role varchar(255) check (role in ('ROLE_STUDENT','ROLE_ADMIN','ROLE_TEACHER','ROLE_MANAGER','ROLE_EDITOR')),
	CONSTRAINT uq_user_roles UNIQUE (user_id, role));
create table username_history (
	id bigint generated by default as identity,
	user_id uuid not null,
	username varchar(255) not null,
	start_at timestamp(6) with time zone not null,
	end_at timestamp(6) with time zone,
	primary key (id));

alter table if exists email_history add constraint FKrn0wehdu7lw8cajbo11kum5h0 foreign key (user_id) references app_user;
alter table if exists user_roles add constraint FK6fql8djp64yp4q9b3qeyhr82b foreign key (user_id) references app_user;
alter table if exists username_history add constraint FKg6clj6rcs9wcqv9lqfi3bwsmu foreign key (user_id) references app_user;

insert into app_user (
    "id",
	"created_at",
	"email",
	"failed_attempts",
	"active",
	"email_verified",
	"last_login_at",
	"last_token_issued_at",
	"password",
	"password_changed_at",
	"prev_login_at",
	"timezone",
	"updated_at",
	"username"
) values (
    '2c5872cb-2e2a-44ed-bcdd-b070f6d46135',
    '2025-05-08 23:40:13.754737+08',
    'kalashnikov@ilogos.ru',
    0,
    True,
    False,
    NULL,
    '2025-05-08 23:40:13.670833+08',
    '$2a$10$nCCmywYHNBelWNA/rbL9Mui5Vx53WZFq90Pa7zgBN7iyvBlGji0wq',
    NULL,
    NULL,
    '+8',
    NULL,
    'ilogos-admin'
);

insert into email_history (
    "email", "end_at", "start_at", "user_id"
) values (
    'kalashnikov@ilogos.ru',
    NULL,
    '2025-05-08 23:40:13.799535+08',
    '2c5872cb-2e2a-44ed-bcdd-b070f6d46135'
);

insert into user_roles (
    "user_id", "role"
) values (
    '2c5872cb-2e2a-44ed-bcdd-b070f6d46135', 'ROLE_ADMIN'
);

insert into username_history (
    "end_at", "start_at", "username", "user_id"
) values (
    NULL,
    '2025-05-08 23:40:13.783999+08',
    'ilogos-admin',
    '2c5872cb-2e2a-44ed-bcdd-b070f6d46135'
);
