spring:
  datasource:
    url: ${AUTH_ILOGOS_DB_URL}
    username: ${DB_ILOGOS_USERNAME}
    password: ${DB_ILOGOS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
    baseline-on-migrate: true
    baseline-version: 0
server:
  port: 8090
jwt:
  secretPath: ${ILOGOS_JWT_PRIVATE}
  publicPath: ${ILOGOS_JWT_PUBLIC}
  accessTokenExpiration: 900000   # 15 minutes
  refreshTokenExpiration: 604800000 # 7 days
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
